name:                childes
version:             0.0.0.0
synopsis:            Ruthe's
description:         Blah
homepage:            http://github.com/jkarni/childes
license:             BSD3
license-file:        LICENSE
author:              Julian K. Arni
maintainer:          jkarni@gmail.com
category:            Language
copyright:           (c) Julian K. Arni
github:              jkarni/childes
tested-with:         GHC == 8.0.1

extra-source-files:
  - package.yaml

ghc-options: -Wall

dependencies:
  - base >= 4.7 && < 4.10
  - hxt
  - xml-lens
  - text
  - xml-conduit
  - cassava
  - time
  - bytestring

default-extensions:
  - AutoDeriveTypeable
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - KindSignatures
  - MultiParamTypeClasses
  - OverloadedStrings
  - StandaloneDeriving
  - RankNTypes
  - ScopedTypeVariables
  - TypeFamilies
  - TypeOperators

library:
  source-dirs:      src
  other-modules:    []

executables:
  childes:
    main:            Main.hs
    source-dirs:     exe
    dependencies:
      - childes
      - directory

#tests:
  #spec:
    #main:            Spec.hs
    #source-dirs:     test
    #dependencies:
      #- hspec > 2 && < 3
      #- QuickCheck >= 2.8 && < 2.9
      #- childes
